"""add indexes

Revision ID: e1d47a492182
Revises: b9372254402e
Create Date: 2025-09-15 19:36:37.918852

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "e1d47a492182"
down_revision: Union[str, Sequence[str], None] = "b9372254402e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_items_created_at"), "items", ["created_at"], unique=False)
    op.create_index(op.f("ix_items_deleted_at"), "items", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_items_end_at"), "items", ["end_at"], unique=False)
    op.create_index(op.f("ix_items_id"), "items", ["id"], unique=False)
    op.create_index(op.f("ix_items_start_at"), "items", ["start_at"], unique=False)
    op.create_index(op.f("ix_items_updated_at"), "items", ["updated_at"], unique=False)
    op.create_index(
        op.f("ix_payments_created_at"), "payments", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_payments_deleted_at"), "payments", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_payments_id"), "payments", ["id"], unique=False)
    op.create_index(op.f("ix_payments_paid_at"), "payments", ["paid_at"], unique=False)
    op.create_index(
        op.f("ix_payments_updated_at"), "payments", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_registrations_created_at"),
        "registrations",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_registrations_deleted_at"),
        "registrations",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(op.f("ix_registrations_id"), "registrations", ["id"], unique=False)
    op.create_index(
        op.f("ix_registrations_updated_at"),
        "registrations",
        ["updated_at"],
        unique=False,
    )
    op.create_index(op.f("ix_users_created_at"), "users", ["created_at"], unique=False)
    op.create_index(op.f("ix_users_deleted_at"), "users", ["deleted_at"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_updated_at"), "users", ["updated_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_updated_at"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_deleted_at"), table_name="users")
    op.drop_index(op.f("ix_users_created_at"), table_name="users")
    op.drop_index(op.f("ix_registrations_updated_at"), table_name="registrations")
    op.drop_index(op.f("ix_registrations_id"), table_name="registrations")
    op.drop_index(op.f("ix_registrations_deleted_at"), table_name="registrations")
    op.drop_index(op.f("ix_registrations_created_at"), table_name="registrations")
    op.drop_index(op.f("ix_payments_updated_at"), table_name="payments")
    op.drop_index(op.f("ix_payments_paid_at"), table_name="payments")
    op.drop_index(op.f("ix_payments_id"), table_name="payments")
    op.drop_index(op.f("ix_payments_deleted_at"), table_name="payments")
    op.drop_index(op.f("ix_payments_created_at"), table_name="payments")
    op.drop_index(op.f("ix_items_updated_at"), table_name="items")
    op.drop_index(op.f("ix_items_start_at"), table_name="items")
    op.drop_index(op.f("ix_items_id"), table_name="items")
    op.drop_index(op.f("ix_items_end_at"), table_name="items")
    op.drop_index(op.f("ix_items_deleted_at"), table_name="items")
    op.drop_index(op.f("ix_items_created_at"), table_name="items")
    # ### end Alembic commands ###
